### PR TITLE
preparations for 0.8.5 release

### PR DESCRIPTION
**Pull request by 01micko**
- replace all occurences of 0.8.4+ with 0.8.5
- configure.ac: bump version from 0.8.4 to 0.8.5
- meson.build: bump version from 0.8.4 to 0.8.5
- subprojects/gtk-layer-shell.wrap: bump revision from b5e0bbc7f2ac632a65db29193fa384baeb23a96c to ca37ef1baa623302dda5fcea200d04e0d9a10578

re #130

### CODE REVIEW

**Comment by 01micko** [comment]
```
gtkdialog -v
gtkdialog version 0.8.5  (C) 2003-2007 Laszlo Pere, 2011-2012 Thunor
Built with support for: GTK+ 3, VTE.
```
### TO DO 

- [ ] wiki

**Comment by step-** [comment]
missing version bump
```
doc/reference/tree.html
192:<td class="wiki">0.8.4</td>
198:<td class="wiki">0.8.4</td>

doc/reference/window.html
140:<td class="wiki">0.8.4</td>
146:<td class="wiki">0.8.4</td>
```

**Comment by step-** [comment]
missing executable permission
```
examples/menubar/menubar
```

**Comment by step-** [comment]
update [AUTHORS](https://github.com/puppylinux-woof-CE/gtkdialog/blob/master/AUTHORS) file
Suggestion: just saying "the woof-CE gtkdialog contributors" is enough (at least for me) since the commit log already documents authorship details.

**Comment by step-** [comment]
Optional: documenting the meson build in [INSTALL](https://github.com/puppylinux-woof-CE/gtkdialog/blob/master/INSTALL)?

**Comment by step-** [comment]
Optional: update [ChangeLog](https://github.com/puppylinux-woof-CE/gtkdialog/blob/master/ChangeLog)? Or maybe just add link to wiki's [Development](https://github.com/puppylinux-woof-CE/gtkdialog/wiki#development) section.

**Comment by 01micko** [comment]
> missing version bump
> 
> ```
> doc/reference/tree.html
> 192:<td class="wiki">0.8.4</td>
> 198:<td class="wiki">0.8.4</td>
> 
> doc/reference/window.html
> 140:<td class="wiki">0.8.4</td>
> 146:<td class="wiki">0.8.4</td>
> ```

I get window but tree? Should be 0.8.5?

**Comment by step-** [comment]
> > missing version bump
> > ```
> > doc/reference/tree.html
> > 192:<td class="wiki">0.8.4</td>
> > 198:<td class="wiki">0.8.4</td>
> > 
> > doc/reference/window.html
> > 140:<td class="wiki">0.8.4</td>
> > 146:<td class="wiki">0.8.4</td>
> > ```
> 
> I get window but tree? Should be 0.8.5?

No, it shouldn't, you're right.
See https://github.com/puppylinux-woof-CE/gtkdialog/blob/90890c32e12b509310634fbf06e1bfc5ae73a177/ChangeLog#L35
and https://github.com/puppylinux-woof-CE/gtkdialog/blob/90890c32e12b509310634fbf06e1bfc5ae73a177/ChangeLog#L16

**Review by step- — APPROVED** [review]

**Comment by zigbert** [comment]
It is incredible to see your effort to bring gtkdialog to GTK3 and Wayland. This brings Puppy into the future. For the moment my days does not allow much effort to our project, - but that's just what is named "life". That may change, and I am excited to read about a new Gtkdialog, and new Puppies.

The last thing I did before I had to pause my Puppy-development, was to move 'Gtkdialog - Tips and tricks' to the wiki. I see now that the wiki is malfunctioning. Hopefully, this is temporarily...

Thank you all!

**Comment by 01micko** [comment]
Hi @zigbert . Glad you could drop by.

I mainly tagged you as a 'reviewer' out of respect as you have probably done more `gtkdialog` scripting than most people. You may or may not get the grasp of the `C` code changes, but hopefully the documented changes are useful to you if/when you get the time.

After the demise of murga forum, 'rockedge', owner of the new forum, together with @jamesbond3142 's expertise have managed to revive the 'old' forum with nearly all of the original content.  Your old 'gtkdialog tips' thread survived. https://oldforum.puppylinux.com/viewtopic.php?t=38608&sid=1dba7ee04f492fecb58948b4cf5f7744

There are problems with 'bitrot' on the wiki as the developers of wikka decided to move on. We are looking for a solution.

Again, thanks for everything. Cheers.

**Comment by zigbert** [comment]
> I mainly tagged you as a 'reviewer' out of respect 
My respect goes back to you, - a rare example of wise leadership.

> hopefully the documented changes are useful to you if/when you get the time
I'll be back

**Comment by JakeSFR** [comment]
I don't feel qualified enough to review all the changes, I'm merely a Gtkdialog user, not developer, but since @step- has given it a green light, it's good enough for me. :)

I haven't done much in Gtkdialog lately, but if I happen to write something new, I'll certainly try to utilize the new features, when appropriate.

Thanks &
Cheers!

**Comment by 01micko** [comment]
Since this is mainly documentation and a version bump it's pretty safe to merge. I'll leave a window of a week or so before release of __0.8.5__ in case of any last minute _bugfix/essential feature_ PRs.

This will give me time to update the _wiki_.

**Pull request merged**
