### PR TITLE
Update documentation for 0.8.5

### PR DESCRIPTION
**Pull request by 01micko**
- general cleanup fixing typos and broken links
- add Gtk3 links along side Gtk2 links where necessary
- made sure all links use https
re #143

### CODE REVIEW

**Comment by step-** [comment]
I found some minor issues in this commit, let me round them up...

**Comment by step-** [comment]
HTML document validation issue: The recommended System Identifier for HTML 4.01 Transitional is http://www.w3.org/TR/html4/loose.dtd.

Solution: either delete the first "s" in "https://www.w3.org/TR/html4/loose.dtd" for all documents or replace the HTML 4.01 Transitional doctype with "<!DOCTYPE html>", which declares the document to be valid HTML5 - it should be anyway.  As far as compatibility, I'd be hard-pressed to find a browser (including lynx) that doesn't do HTML5.

Other errors found with the [new validator](https://github.com/validator/validator):

```
button.html":399.25-399.28: error: Stray end tag “a”.
checkbox.html":380.25-380.28: error: Stray end tag “a”.
chooser.html":348.25-348.28: error: Stray end tag “a”.
colorbutton.html":366.25-366.28: error: Stray end tag “a”.
comboboxentry.html":417.25-417.28: error: Stray end tag “a”.
combobox.html":282.25-282.28: error: Stray end tag “a”.
comboboxtext.html":416.25-416.28: error: Stray end tag “a”.
edit.html":360.25-360.28: error: Stray end tag “a”.
entry.html":431.25-431.28: error: Stray end tag “a”.
eventbox.html":265.25-265.28: error: Stray end tag “a”.
expander.html":368.25-368.28: error: Stray end tag “a”.
fontbutton.html":367.25-367.28: error: Stray end tag “a”.
frame.html":284.25-284.28: error: Stray end tag “a”.
hbox.html":315.25-315.28: error: Stray end tag “a”.
hscale.html":280.24-280.27: error: Stray end tag “a”.
hscale.html":280.24-280.32: error: Stray end tag “em”.
hscale.html":392.25-392.28: error: Stray end tag “a”.
list.html":398.25-398.28: error: Stray end tag “a”.
menubar.html":265.25-265.28: error: Stray end tag “a”.
menu.html":269.35-269.38: error: Stray end tag “a”.
menu.html":363.25-363.28: error: Stray end tag “a”.
menuitem.html":305.357-305.360: error: Stray end tag “a”.
menuitem.html":406.25-406.28: error: Stray end tag “a”.
notebook.html":341.25-341.28: error: Stray end tag “a”.
pixmap.html":329.25-329.28: error: Stray end tag “a”.
progressbar.html":297.25-297.28: error: Stray end tag “a”.
radiobutton.html":380.25-380.28: error: Stray end tag “a”.
spinbutton.html":394.25-394.28: error: Stray end tag “a”.
statusbar.html":360.25-360.28: error: Stray end tag “a”.
table.html":453.25-453.28: error: Stray end tag “a”.
terminal.html":438.25-438.28: error: Stray end tag “a”.
text.html":146.6-147.5: error: Misplaced non-space characters inside a table.
text.html":146.6-147.5: error fatal: Cannot recover after last error. Any further errors will be ignored.
timer.html":335.25-335.28: error: Stray end tag “a”.
togglebutton.html":413.25-413.28: error: Stray end tag “a”.
tree.html":534.25-534.28: error: Stray end tag “a”.
vbox.html":315.25-315.28: error: Stray end tag “a”.
vscale.html":280.24-280.27: error: Stray end tag “a”.
vscale.html":280.24-280.32: error: Stray end tag “em”.
vscale.html":392.25-392.28: error: Stray end tag “a”.
window.html":336.25-336.28: error: Stray end tag “a”.
```

**Comment by step-** [comment]
I really like that you took the time to add links for _both_ GTK versions.

**Comment by step-** [comment]
I clicked the Gtk2/Gtk3 links in the Signals section of a couple of documents. The Gtk3 links returned a 502 error page.  Specifically, I clicked:
* [in button.html](https://docs.gtk.org/gtk3/method.Button.clicked.html in button.html)
* [in chooser.html](https://docs.gtk.org/gtk3/signal.FileChooser.file-activated.html)

I didn't try any more links.

**Comment by step-** [comment]
I thought you wanted to replace `0.8.4+` with `0.8.5` throughout.  Instead I found:
```
# grep -F '0.8.4+' *.html
button.html:<td class="wiki">0.8.4+</td>
button.html:<td class="wiki">0.8.4+</td>
checkbox.html:<td class="wiki">0.8.4+</td>
checkbox.html:<td class="wiki">0.8.4+</td>
chooser.html:<td class="wiki">0.8.4+</td>
chooser.html:<td class="wiki">0.8.4+</td>
chooser.html:<td class="wiki">0.8.4+</td>
chooser.html:<td class="wiki">0.8.4+</td>
chooser.html:<td class="wiki">0.8.4+</td>
colorbutton.html:<td class="wiki">0.8.4+</td>
colorbutton.html:<td class="wiki">0.8.4+</td>
comboboxentry.html:<td class="wiki">0.8.4+</td>
comboboxentry.html:<td class="wiki">0.8.4+</td>
combobox.html:<td class="wiki">0.8.4+</td>
combobox.html:<td class="wiki">0.8.4+</td>
comboboxtext.html:<td class="wiki">0.8.4+</td>
comboboxtext.html:<td class="wiki">0.8.4+</td>
edit.html:<td class="wiki">0.8.4+</td>
edit.html:<td class="wiki">0.8.4+</td>
edit.html:<td class="wiki">0.8.4+</td>
entry.html:<td class="wiki">0.8.4+</td>
entry.html:<td class="wiki">0.8.4+</td>
eventbox.html:<td class="wiki">0.8.4+</td>
eventbox.html:<td class="wiki">0.8.4+</td>
expander.html:<td class="wiki">0.8.4+</td>
expander.html:<td class="wiki">0.8.4+</td>
fontbutton.html:<td class="wiki">0.8.4+</td>
fontbutton.html:<td class="wiki">0.8.4+</td>
frame.html:<td class="wiki">0.8.4+</td>
frame.html:<td class="wiki">0.8.4+</td>
hbox.html:<td class="wiki">0.8.4+</td>
hbox.html:<td class="wiki">0.8.4+</td>
hscale.html:<td class="wiki">0.8.4+</td>
hscale.html:<td class="wiki">0.8.4+</td>
list.html:<td class="wiki">0.8.4+</td>
list.html:<td class="wiki">0.8.4+</td>
menubar.html:<td class="wiki">0.8.4+</td>
menubar.html:<td class="wiki">0.8.4+</td>
menu.html:<td class="wiki">0.8.4+</td>
menu.html:<td class="wiki">0.8.4+</td>
menuitem.html:<td class="wiki">0.8.4+</td>
menuitem.html:<td class="wiki">0.8.4+</td>
notebook.html:<td class="wiki">0.8.4+</td>
notebook.html:<td class="wiki">0.8.4+</td>
pixmap.html:<td class="wiki">0.8.4+</td>
pixmap.html:<td class="wiki">0.8.4+</td>
progressbar.html:<td class="wiki">0.8.4+</td>
progressbar.html:<td class="wiki">0.8.4+</td>
radiobutton.html:<td class="wiki">0.8.4+</td>
radiobutton.html:<td class="wiki">0.8.4+</td>
spinbutton.html:<td class="wiki">0.8.4+</td>
spinbutton.html:<td class="wiki">0.8.4+</td>
statusbar.html:<td class="wiki">0.8.4+</td>
statusbar.html:<td class="wiki">0.8.4+</td>
table.html:<td class="wiki">0.8.4+</td>
table.html:<td class="wiki">0.8.4+</td>
terminal.html:<td class="wiki">0.8.4+</td>
terminal.html:<td class="wiki">0.8.4+</td>
text.html:<td class="wiki">0.8.4+</td>
text.html:<td class="wiki">0.8.4+</td>
text.html:<td class="wiki">0.8.4+</td>
text.html:<td class="wiki">0.8.4+</td>
text.html:<td class="wiki">0.8.4+</td>
text.html:<td class="wiki">0.8.4+</td>
text.html:<td class="wiki">0.8.4+</td>
text.html:<td class="wiki">0.8.4+</td>
text.html:<td class="wiki">0.8.4+</td>
timer.html:<td class="wiki">0.8.4+</td>
timer.html:<td class="wiki">0.8.4+</td>
togglebutton.html:<td class="wiki">0.8.4+</td>
togglebutton.html:<td class="wiki">0.8.4+</td>
tree.html:<td class="wiki">0.8.4+</td>
tree.html:<td class="wiki">0.8.4+</td>
vbox.html:<td class="wiki">0.8.4+</td>
vbox.html:<td class="wiki">0.8.4+</td>
vscale.html:<td class="wiki">0.8.4+</td>
vscale.html:<td class="wiki">0.8.4+</td>
window.html:<td class="wiki">0.8.4+</td>
window.html:<td class="wiki">0.8.4+</td>
```
```
# grep -F '0.8.5' *.html
terminal.html:<td class="wiki">0.8.5, gtk3 only</td>
```

**Comment by 01micko** [comment]
> I clicked the Gtk2/Gtk3 links in the Signals section of a couple of documents. The Gtk3 links returned a 502 error page. Specifically, I clicked:
> 
> * [in button.html](https://docs.gtk.org/gtk3/method.Button.clicked.html)
> * [in chooser.html](https://docs.gtk.org/gtk3/signal.FileChooser.file-activated.html)
> 
> I didn't try any more links. _edit: I tried more Gtk3 signal links - they all lead to error 502._

I can't reproduce I'm afraid. Temporary internet error?

**Comment by 01micko** [comment]
> I thought you wanted to replace `0.8.4+` with `0.8.5` throughout. Instead I found:
> 
> ```
> # grep -F '0.8.4+' *.html
> button.html:<td class="wiki">0.8.4+</td>
> button.html:<td class="wiki">0.8.4+</td>
> checkbox.html:<td class="wiki">0.8.4+</td>
> checkbox.html:<td class="wiki">0.8.4+</td>
> chooser.html:<td class="wiki">0.8.4+</td>
> chooser.html:<td class="wiki">0.8.4+</td>
> chooser.html:<td class="wiki">0.8.4+</td>
> chooser.html:<td class="wiki">0.8.4+</td>
> chooser.html:<td class="wiki">0.8.4+</td>
> colorbutton.html:<td class="wiki">0.8.4+</td>
> colorbutton.html:<td class="wiki">0.8.4+</td>
> comboboxentry.html:<td class="wiki">0.8.4+</td>
> comboboxentry.html:<td class="wiki">0.8.4+</td>
> combobox.html:<td class="wiki">0.8.4+</td>
> combobox.html:<td class="wiki">0.8.4+</td>
> comboboxtext.html:<td class="wiki">0.8.4+</td>
> comboboxtext.html:<td class="wiki">0.8.4+</td>
> edit.html:<td class="wiki">0.8.4+</td>
> edit.html:<td class="wiki">0.8.4+</td>
> edit.html:<td class="wiki">0.8.4+</td>
> entry.html:<td class="wiki">0.8.4+</td>
> entry.html:<td class="wiki">0.8.4+</td>
> eventbox.html:<td class="wiki">0.8.4+</td>
> eventbox.html:<td class="wiki">0.8.4+</td>
> expander.html:<td class="wiki">0.8.4+</td>
> expander.html:<td class="wiki">0.8.4+</td>
> fontbutton.html:<td class="wiki">0.8.4+</td>
> fontbutton.html:<td class="wiki">0.8.4+</td>
> frame.html:<td class="wiki">0.8.4+</td>
> frame.html:<td class="wiki">0.8.4+</td>
> hbox.html:<td class="wiki">0.8.4+</td>
> hbox.html:<td class="wiki">0.8.4+</td>
> hscale.html:<td class="wiki">0.8.4+</td>
> hscale.html:<td class="wiki">0.8.4+</td>
> list.html:<td class="wiki">0.8.4+</td>
> list.html:<td class="wiki">0.8.4+</td>
> menubar.html:<td class="wiki">0.8.4+</td>
> menubar.html:<td class="wiki">0.8.4+</td>
> menu.html:<td class="wiki">0.8.4+</td>
> menu.html:<td class="wiki">0.8.4+</td>
> menuitem.html:<td class="wiki">0.8.4+</td>
> menuitem.html:<td class="wiki">0.8.4+</td>
> notebook.html:<td class="wiki">0.8.4+</td>
> notebook.html:<td class="wiki">0.8.4+</td>
> pixmap.html:<td class="wiki">0.8.4+</td>
> pixmap.html:<td class="wiki">0.8.4+</td>
> progressbar.html:<td class="wiki">0.8.4+</td>
> progressbar.html:<td class="wiki">0.8.4+</td>
> radiobutton.html:<td class="wiki">0.8.4+</td>
> radiobutton.html:<td class="wiki">0.8.4+</td>
> spinbutton.html:<td class="wiki">0.8.4+</td>
> spinbutton.html:<td class="wiki">0.8.4+</td>
> statusbar.html:<td class="wiki">0.8.4+</td>
> statusbar.html:<td class="wiki">0.8.4+</td>
> table.html:<td class="wiki">0.8.4+</td>
> table.html:<td class="wiki">0.8.4+</td>
> terminal.html:<td class="wiki">0.8.4+</td>
> terminal.html:<td class="wiki">0.8.4+</td>
> text.html:<td class="wiki">0.8.4+</td>
> text.html:<td class="wiki">0.8.4+</td>
> text.html:<td class="wiki">0.8.4+</td>
> text.html:<td class="wiki">0.8.4+</td>
> text.html:<td class="wiki">0.8.4+</td>
> text.html:<td class="wiki">0.8.4+</td>
> text.html:<td class="wiki">0.8.4+</td>
> text.html:<td class="wiki">0.8.4+</td>
> text.html:<td class="wiki">0.8.4+</td>
> timer.html:<td class="wiki">0.8.4+</td>
> timer.html:<td class="wiki">0.8.4+</td>
> togglebutton.html:<td class="wiki">0.8.4+</td>
> togglebutton.html:<td class="wiki">0.8.4+</td>
> tree.html:<td class="wiki">0.8.4+</td>
> tree.html:<td class="wiki">0.8.4+</td>
> vbox.html:<td class="wiki">0.8.4+</td>
> vbox.html:<td class="wiki">0.8.4+</td>
> vscale.html:<td class="wiki">0.8.4+</td>
> vscale.html:<td class="wiki">0.8.4+</td>
> window.html:<td class="wiki">0.8.4+</td>
> window.html:<td class="wiki">0.8.4+</td>
> ```
> 
> ```
> # grep -F '0.8.5' *.html
> terminal.html:<td class="wiki">0.8.5, gtk3 only</td>
> ```

I'm confused here, because 

```
/mnt/home/micko/gtkdialog/doc/reference$ git branch
* doc-update
  master
  readme-fix
/mnt/home/micko/gtkdialog/doc/reference$ grep -F '0.8.5' *.html
button.html:<td class="wiki">0.8.5</td>
button.html:<td class="wiki">0.8.5</td>
checkbox.html:<td class="wiki">0.8.5</td>
checkbox.html:<td class="wiki">0.8.5</td>
chooser.html:<td class="wiki">0.8.5</td>
chooser.html:<td class="wiki">0.8.5</td>
chooser.html:<td class="wiki">0.8.5</td>
chooser.html:<td class="wiki">0.8.5</td>
chooser.html:<td class="wiki">0.8.5</td>
colorbutton.html:<td class="wiki">0.8.5</td>
colorbutton.html:<td class="wiki">0.8.5</td>
comboboxentry.html:<td class="wiki">0.8.5</td>
comboboxentry.html:<td class="wiki">0.8.5</td>
combobox.html:<td class="wiki">0.8.5</td>
combobox.html:<td class="wiki">0.8.5</td>
comboboxtext.html:<td class="wiki">0.8.5</td>
comboboxtext.html:<td class="wiki">0.8.5</td>
edit.html:<td class="wiki">0.8.5</td>
edit.html:<td class="wiki">0.8.5</td>
edit.html:<td class="wiki">0.8.5</td>
entry.html:<td class="wiki">0.8.5</td>
entry.html:<td class="wiki">0.8.5</td>
eventbox.html:<td class="wiki">0.8.5</td>
eventbox.html:<td class="wiki">0.8.5</td>
expander.html:<td class="wiki">0.8.5</td>
expander.html:<td class="wiki">0.8.5</td>
fontbutton.html:<td class="wiki">0.8.5</td>
fontbutton.html:<td class="wiki">0.8.5</td>
frame.html:<td class="wiki">0.8.5</td>
frame.html:<td class="wiki">0.8.5</td>
hbox.html:<td class="wiki">0.8.5</td>
hbox.html:<td class="wiki">0.8.5</td>
hscale.html:<td class="wiki">0.8.5</td>
hscale.html:<td class="wiki">0.8.5</td>
list.html:<td class="wiki">0.8.5</td>
list.html:<td class="wiki">0.8.5</td>
menubar.html:<td class="wiki">0.8.5</td>
menubar.html:<td class="wiki">0.8.5</td>
menu.html:<td class="wiki">0.8.5</td>
menu.html:<td class="wiki">0.8.5</td>
menuitem.html:<td class="wiki">0.8.5</td>
menuitem.html:<td class="wiki">0.8.5</td>
notebook.html:<td class="wiki">0.8.5</td>
notebook.html:<td class="wiki">0.8.5</td>
pixmap.html:<td class="wiki">0.8.5</td>
pixmap.html:<td class="wiki">0.8.5</td>
progressbar.html:<td class="wiki">0.8.5</td>
progressbar.html:<td class="wiki">0.8.5</td>
radiobutton.html:<td class="wiki">0.8.5</td>
radiobutton.html:<td class="wiki">0.8.5</td>
spinbutton.html:<td class="wiki">0.8.5</td>
spinbutton.html:<td class="wiki">0.8.5</td>
statusbar.html:<td class="wiki">0.8.5</td>
statusbar.html:<td class="wiki">0.8.5</td>
table.html:<td class="wiki">0.8.5</td>
table.html:<td class="wiki">0.8.5</td>
terminal.html:<td class="wiki">0.8.5, gtk3 only</td>
terminal.html:<td class="wiki">0.8.5</td>
terminal.html:<td class="wiki">0.8.5</td>
text.html:<td class="wiki">0.8.5</td>
text.html:<td class="wiki">0.8.5</td>
text.html:<td class="wiki">0.8.5</td>
text.html:<td class="wiki">0.8.5</td>
text.html:<td class="wiki">0.8.5</td>
text.html:<td class="wiki">0.8.5</td>
text.html:<td class="wiki">0.8.5</td>
text.html:<td class="wiki">0.8.5</td>
text.html:<td class="wiki">0.8.5</td>
timer.html:<td class="wiki">0.8.5</td>
timer.html:<td class="wiki">0.8.5</td>
togglebutton.html:<td class="wiki">0.8.5</td>
togglebutton.html:<td class="wiki">0.8.5</td>
tree.html:<td class="wiki">0.8.5</td>
tree.html:<td class="wiki">0.8.5</td>
vbox.html:<td class="wiki">0.8.5</td>
vbox.html:<td class="wiki">0.8.5</td>
vscale.html:<td class="wiki">0.8.5</td>
vscale.html:<td class="wiki">0.8.5</td>
window.html:<td class="wiki">0.8.5</td>
window.html:<td class="wiki">0.8.5</td>
window.html:<td class="wiki">0.8.5</td>
window.html:<td class="wiki">0.8.5</td>
window.html:<td class="wiki">0.8.5</td>
/mnt/home/micko/gtkdialog/doc/reference$ 

```

On my `doc-update` branch I certainly have 0.8.5 in `window.html`

20220327_06h33m38s_grim

**Comment by step-** [comment]
> > I clicked the Gtk2/Gtk3 links in the Signals section of a couple of documents. The Gtk3 links returned a 502 error page. Specifically, I clicked:
> > 
> > * [in button.html](https://docs.gtk.org/gtk3/method.Button.clicked.html)
> > * [in chooser.html](https://docs.gtk.org/gtk3/signal.FileChooser.file-activated.html)
> > 
> > I didn't try any more links. _edit: I tried more Gtk3 signal links - they all lead to error 502._
> 
> I can't reproduce I'm afraid. Temporary internet error?

Definitely, I can't reproduce either now.  All's well that ends well!

**Comment by 01micko** [comment]
> HTML document validation issue: The recommended System Identifier for HTML 4.01 Transitional is http://www.w3.org/TR/html4/loose.dtd.
> 
> Solution: either delete the first "s" in "https://www.w3.org/TR/html4/loose.dtd" for all documents or replace the HTML 4.01 Transitional doctype with "", which declares the document to be valid HTML5 - it should be anyway. As far as compatibility, I'd be hard-pressed to find a browser (including lynx) that doesn't do HTML5.
> 
> Other errors found with the [new validator](https://github.com/validator/validator):
> 

Thanks; a simple sed operation will take care of the stray `</a>` tags, and then there is only a few more errors so should be easy fix.

Can it be just

```html
<!DOCTYPE html>
```

or do I need

```html
<html lang="en">
```
also

**Comment by step-** [comment]
> On my `doc-update` branch I certainly have 0.8.5 in `window.html`

Then it's my bad. I kind of know what must have happened.  I didn't pull your branch to review it; I just downloaded the patch file for this PR and applied it to my local repo.  I must have applied it to a branch that lacked some recent commits of yours.

**Comment by step-** [comment]
> ```
> <!DOCTYPE html>
> ```

is sufficient.  The `lang` attribute is optional.  When you're done try validating by file upload at [W3C validator service](https://validator.w3.org) - just one of the files will be enough.

**Comment by 01micko** [comment]
> > ```
> > <!DOCTYPE html>
> > ```
> 
> is sufficient. The `lang` attribute is optional. When you're done try validating by file upload at [W3C validator service](https://validator.w3.org) - just one of the files will be enough.

The broken files with 2+ errors will have the links restored; probably a hangover of my wiki conversion a couple of months ago.

**Comment by 01micko** [comment]
Ok, all issues _should_ now be fixed here and in the wiki so I force-pushed (you wont see previous commit)

**Comment by 01micko** [comment]
Just going through the issues, this PR closes #114 #130 and #143

**Comment by 01micko** [comment]
I'm thinking this is _ok_ so merging.

If it's a rainy day tomorrow (I'm a construction worker :rofl: ) I'll release `0.8.5` tomorrow.

**Pull request merged**
