### PR TITLE
Add layer shell support

### PR DESCRIPTION
**Pull request by dimkr**
To see it in action: add `layer="overlay"` to the `<window>` tag of /usr/lib/gtkdialog/box_splash.

This change is backward-compatible - current gtkdialog releases ignore this new attribute.

### CODE REVIEW

**Comment by 01micko** [comment]
I have a problem building:

```
/root/gtkdialog/build/../src/automaton.c:919: undefined reference to `gtk_widget_set_uposition'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**Comment by dimkr** [comment]
> I have a problem building:
> 
> ```
> /root/gtkdialog/build/../src/automaton.c:919: undefined reference to `gtk_widget_set_uposition'
> collect2: error: ld returned 1 exit status
> ninja: build stopped: subcommand failed.
> ```

Yes, there's a bug (unrelated to this branch). Probably a missing `#ifdef`.

Run meson with `--buildtype=release`.

**Comment by 01micko** [comment]
> Yes, there's a bug (unrelated to this branch). Probably a missing `#ifdef`.
> 
> Run meson with `--buildtype=release`.

That built ok :smile:

**Comment by dimkr** [comment]
https://github.com/puppylinux-woof-CE/gtkdialog/pull/103 😄

**Comment by 01micko** [comment]
20211110_06h32m06s_grim

:smile:

**Review by 01micko — APPROVED** [review]

**Pull request merged**
