### PR TITLE
Update automaton.c. This allows correct element stack in aarch64 and mac

### LINKED ISSUE #84: Here is a fix for aarch64
Hi guys, I have a patch for you. gtkdialog renders widgets incorrectly on aarch64, this link explains and has a patch:

http://bkhome.org/news/201807/fix-widget-order-for-gtkdialog-aarch64.html

### PR DESCRIPTION
**Pull request by 01micko**
partially addresses #81
closes #84

### CODE REVIEW

**Comment by 01micko** [comment]
@woodenshoe-wi can you confirm that this change is safe? Looks ok to me.

Also the patch in #81 to `variables.c` looks sane to me but I left it off for the time being.

**Comment by woodenshoe-wi** [comment]
I’ve never run a 64bit OS on my Pis and I don’t have a Mac PC, so I can’t test it but it looks okay to me too.

**Comment by 01micko** [comment]
Thanks @woodenshoe-wi 

I'll ping @jamesbond3142 for confirmation before I merge as he was the author of the original `__arm__` patch.

**Comment by 01micko** [comment]
Downloaded Barry's pyro aarch64 build for pi and ran it on the pi3. Compiled and was wrong :exclamation: -  then I fixed the typo and the stacking is correct. :disappointed_relieved:

**Comment by 01micko** [comment]
I'm thinking this is safe to merge now that I tested `aarch64`.

**Pull request merged**
