### PR TITLE
fix package build not using new lexical features

### PR DESCRIPTION
**Pull request by step-**
Files gtkdialog_lexer.c and gtkdialog_parser.[ch] aren't source files;
flex and bison generate these files from their corresponding .l and .y
sources as part of making the target. Leaving the .[ch] files in the
repo can lead to a bad build. If the repo is downloaded from github to
build from sources, all files share the same timestamp, therefore the
lexer and parser are built from the existing - and possibly old - .[ch]
files instead of from [.ly] files as they should be.

### CODE REVIEW

**Comment by step-** [comment]
@01micko, what etiquette do you want me to follow as regards commits to this repo?  You hinted I could merge PRs, did you mean it or do you want to merge?

**Comment by 01micko** [comment]
> @01micko, what etiquette do you want me to follow as regards commits to this repo? You hinted I could merge PRs, did you mean it or do you want to merge?

Normally we issue  PR and request a review, and merge it our selves when reviews are satisfied. I'll merge this one.

**Comment by dimkr** [comment]
Something is wrong with the autotools build, still not sure what causes this:

```
gtkdialog.c:48:10: fatal error: gtkdialog_parser.h: No such file or directory
   48 | #include "gtkdialog_parser.h"
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:549: gtkdialog.o] Error 1
```

**Comment by step-** [comment]
Hmm, when #131 was committed it passed the autotools build.  Now is it failing on github or in your private build environment? Try to make really clean, no stray `.o` files, etc.  Try also regenerating `aclocal.m4`.

**Pull request merged**
